### ISSUE TITLE
Authentication doesnt work with Safari Tampermonkey

### ISSUE THREAD

**Issue by jamesanderson16** [cachetur-no/cachetur-assistant#20]
Hi,

I have just downloaded and installed the Cachetur-assistant with Tampermonkey on Mac OS Safari, and it comes up with a message saying on both geocaching.com and project-gc.com "cachetur.no You are not logged in on cachetur.no
The Cachetur Assistant has been deactivated" but I am logged into Cachetur and I haven't deactivated the app,

could this possibly be rectified, please?

Thanks

James A

**Comment by cghove** [comment]
Unfortunatly, this is due to policies inside of Safari set by Apple, so the Assistant will for the time being not support Safari
